improve path handling alexeiskachykhin/flc#1
alexeiskachykhin/flc pull request #2
Opened 2016-09-20 08:27 UTC by endel

Hey @alexeiskachykhin, still testing out your tool. :)

Now it works on OSX for me. Just fixed some minor issues with directory separator.

Thanks! Cheers

2016-09-20 08:30 UTC, endel commented
Now the command-line is evaluating the full path, even if you provide a relative one (https://github.com/endel/flc/blob/master/src/cli/FlaCompiler.js#L17-L18), I guess this should be fine on Windows as well.

2016-09-21 10:13 UTC, alexeiskachykhin commented
@endel it looks great, thank you for your work :+1:  I'll take some time today to review.

2016-09-21 19:06 UTC, alexeiskachykhin commented on src/cli/FlaCompiler.js
> +            outputDirectory: path.resolve(config.outputDirectory),
@endel looks like a really good way to address relative path. We should do the same for `logFile`, `errorFile` and `commandFile` otherwise communication between Animate and CLI will not work as Animate needs to have absolute path to these files. Here is what I suggest:

```
this._internalConfig = {
    interactiveCompiler: config.interactiveCompiler,
    inputDirectory: path.resolve(config.inputDirectory),
    outputDirectory: path.resolve(config.outputDirectory),
    includePattern: config.includePattern,
    debug: config.debug
};

Object.assign(this._internalConfig, {
    buildPlan: path.join(__dirname, '..', 'automation', 'plans', 'AS3.jsfl'),
    logFile: path.join(this._internalConfig.outputDirectory, 'info.txt'),
    errorFile: path.join(this._internalConfig.outputDirectory, 'error.txt'),
    commandFile: path.join(this._internalConfig.outputDirectory, 'commands.txt')
});
```

Here I moved all calculated properties under object assign so that they can assess `_internalConfig`.

2016-09-21 19:08 UTC, alexeiskachykhin requested changes
Thank you awesome work!

2016-09-26 08:50 UTC, endel commented on src/cli/FlaCompiler.js
> +            outputDirectory: path.resolve(config.outputDirectory),
Hey! Thanks for your feedback. I just updated to evaluate the full path on `Host.js` instead of `FlaCompiler.js`, now it should be available everywhere :)

2016-09-26 18:13 UTC, alexeiskachykhin approved these changes

2016-09-26 18:15 UTC, alexeiskachykhin commented on src/cli/FlaCompiler.js
> +            outputDirectory: path.resolve(config.outputDirectory),
@endel looks great thank you :) I'm going to merge it. Now when there is code in `Host.js` I'll take some time to rethink responsibilities of `Host.js` and `FlaCompiler.js`.

2016-09-26 18:15 UTC, merged

2016-09-26 19:03 UTC, endel commented on src/cli/FlaCompiler.js
> +            outputDirectory: path.resolve(config.outputDirectory),
Great, thanks!